[2024-04-13T01:24:56.717+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T01:24:56.240838+00:00 [queued]>
[2024-04-13T01:24:56.729+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T01:24:56.240838+00:00 [queued]>
[2024-04-13T01:24:56.729+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-13T01:24:56.745+0000] {taskinstance.py:2217} INFO - Executing <Task(DockerOperator): print_message> on 2024-04-13 01:24:56.240838+00:00
[2024-04-13T01:24:56.750+0000] {standard_task_runner.py:60} INFO - Started process 3154 to run task
[2024-04-13T01:24:56.752+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example-docker-operator-dag', 'print_message', 'manual__2024-04-13T01:24:56.240838+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/project/dag.py', '--cfg-path', '/tmp/tmpnhdnsu8_']
[2024-04-13T01:24:56.752+0000] {standard_task_runner.py:88} INFO - Job 42: Subtask print_message
[2024-04-13T01:24:56.785+0000] {task_command.py:423} INFO - Running <TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T01:24:56.240838+00:00 [running]> on host 54de63e8b577
[2024-04-13T01:24:56.847+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example-docker-operator-dag' AIRFLOW_CTX_TASK_ID='print_message' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T01:24:56.240838+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-13T01:24:56.240838+00:00'
[2024-04-13T01:24:56.859+0000] {docker.py:359} INFO - Starting docker container from image docker-operator-etl:1.0
[2024-04-13T01:24:57.171+0000] {docker.py:429} INFO - iniciando processoamento - MONITORAMENTO_GRAFANA
I'm 3 running inside a docker Container, but outside of *** schedule container
DW_HOST: 172.1.12.34\DW
DW_PORT: 1433
DW_DATABASE: trusted
DW_USER: engdados
DW_PASSWORD: senha_do_dw
MYSQL_GRAFANA_HOST: 192.25.2.197
MSYQL_GRAFANA_DB: database
MYSQL_GRAFANA_PORT: 3306
MYSQL_GRAFANA_USER: engdados
MYSQL_GRAFANA_PASSWORD: senha_do_grafana
I'm running inside a docker Container, but outside of *** schedule container
Printing Docker variables:
DW_HOST: 172.1.12.34\DW
DW_PORT: 1433
DW_DATABASE: trusted
DW_USER: engdados
DW_PASSWORD: senha_do_dw
MYSQL_GRAFANA_HOST: 192.25.2.197
MYSQL_GRAFANA_DB: None
MYSQL_GRAFANA_PORT: 3306
MYSQL_GRAFANA_USER: engdados
MYSQL_GRAFANA_PASSWORD: senha_do_grafana
[2024-04-13T01:24:57.349+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=example-docker-operator-dag, task_id=print_message, execution_date=20240413T012456, start_date=20240413T012456, end_date=20240413T012457
[2024-04-13T01:24:57.366+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-13T01:24:57.379+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
