[2024-04-13T01:04:15.542+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T01:04:14.783036+00:00 [queued]>
[2024-04-13T01:04:15.548+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T01:04:14.783036+00:00 [queued]>
[2024-04-13T01:04:15.548+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-13T01:04:15.559+0000] {taskinstance.py:2217} INFO - Executing <Task(DockerOperator): print_message> on 2024-04-13 01:04:14.783036+00:00
[2024-04-13T01:04:15.563+0000] {standard_task_runner.py:60} INFO - Started process 2825 to run task
[2024-04-13T01:04:15.565+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example-docker-operator-dag', 'print_message', 'manual__2024-04-13T01:04:14.783036+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/project/dag.py', '--cfg-path', '/tmp/tmppeioazic']
[2024-04-13T01:04:15.566+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask print_message
[2024-04-13T01:04:15.598+0000] {task_command.py:423} INFO - Running <TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T01:04:14.783036+00:00 [running]> on host 54de63e8b577
[2024-04-13T01:04:15.655+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example-docker-operator-dag' AIRFLOW_CTX_TASK_ID='print_message' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T01:04:14.783036+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-13T01:04:14.783036+00:00'
[2024-04-13T01:04:15.667+0000] {docker.py:359} INFO - Starting docker container from image docker-operator-etl:1.0
[2024-04-13T01:04:15.945+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/app/src/main.py", line 5, in <module>
    from operations.DockerVariables import mainer
ModuleNotFoundError: No module named 'operations.DockerVariables'
[2024-04-13T01:04:16.174+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-04-13T01:04:16.176+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=example-docker-operator-dag, task_id=print_message, execution_date=20240413T010414, start_date=20240413T010415, end_date=20240413T010416
[2024-04-13T01:04:16.183+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task print_message (Docker container failed: {'StatusCode': 1}; 2825)
[2024-04-13T01:04:16.219+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-13T01:04:16.233+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
