[2024-04-13T01:15:36.848+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T01:15:36.330826+00:00 [queued]>
[2024-04-13T01:15:36.857+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T01:15:36.330826+00:00 [queued]>
[2024-04-13T01:15:36.858+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-13T01:15:36.875+0000] {taskinstance.py:2217} INFO - Executing <Task(DockerOperator): print_message> on 2024-04-13 01:15:36.330826+00:00
[2024-04-13T01:15:36.882+0000] {standard_task_runner.py:60} INFO - Started process 2999 to run task
[2024-04-13T01:15:36.886+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example-docker-operator-dag', 'print_message', 'manual__2024-04-13T01:15:36.330826+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/project/dag.py', '--cfg-path', '/tmp/tmp05vy_ju7']
[2024-04-13T01:15:36.887+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask print_message
[2024-04-13T01:15:36.928+0000] {task_command.py:423} INFO - Running <TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T01:15:36.330826+00:00 [running]> on host 54de63e8b577
[2024-04-13T01:15:36.995+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example-docker-operator-dag' AIRFLOW_CTX_TASK_ID='print_message' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T01:15:36.330826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-13T01:15:36.330826+00:00'
[2024-04-13T01:15:37.006+0000] {docker.py:359} INFO - Starting docker container from image docker-operator-etl:1.0
[2024-04-13T01:15:37.267+0000] {docker.py:429} INFO - iniciando processoamento - MONITORAMENTO_GRAFANA
I'm 3 running inside a docker Container, but outside of *** schedule container
DW_HOST: 172.1.12.34\DW
DW_PORT: 1433
DW_DATABASE: trusted
DW_USER: engdados
DW_PASSWORD: senha_do_dw
MYSQL_GRAFANA_HOST: 192.25.2.197
MSYQL_GRAFANA_DB: database
MYSQL_GRAFANA_PORT: 3306
MYSQL_GRAFANA_USER: engdados
MYSQL_GRAFANA_PASSWORD: senha_do_grafana
[2024-04-13T01:15:37.268+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/app/src/main.py", line 16, in <module>
    main()
  File "/app/src/main.py", line 11, in main
    data2 = DockerVariables().my_function()
AttributeError: 'DockerVariables' object has no attribute 'my_function'
[2024-04-13T01:15:37.471+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-04-13T01:15:37.474+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=example-docker-operator-dag, task_id=print_message, execution_date=20240413T011536, start_date=20240413T011536, end_date=20240413T011537
[2024-04-13T01:15:37.481+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 36 for task print_message (Docker container failed: {'StatusCode': 1}; 2999)
[2024-04-13T01:15:37.500+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-13T01:15:37.517+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
