[2024-04-13T00:55:10.230+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T00:55:09.780717+00:00 [queued]>
[2024-04-13T00:55:10.240+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T00:55:09.780717+00:00 [queued]>
[2024-04-13T00:55:10.240+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-13T00:55:10.253+0000] {taskinstance.py:2217} INFO - Executing <Task(DockerOperator): print_message> on 2024-04-13 00:55:09.780717+00:00
[2024-04-13T00:55:10.259+0000] {standard_task_runner.py:60} INFO - Started process 2676 to run task
[2024-04-13T00:55:10.263+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example-docker-operator-dag', 'print_message', 'manual__2024-04-13T00:55:09.780717+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/project/dag.py', '--cfg-path', '/tmp/tmp1wmzyqht']
[2024-04-13T00:55:10.264+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask print_message
[2024-04-13T00:55:10.313+0000] {task_command.py:423} INFO - Running <TaskInstance: example-docker-operator-dag.print_message manual__2024-04-13T00:55:09.780717+00:00 [running]> on host 54de63e8b577
[2024-04-13T00:55:10.383+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example-docker-operator-dag' AIRFLOW_CTX_TASK_ID='print_message' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T00:55:09.780717+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-13T00:55:09.780717+00:00'
[2024-04-13T00:55:10.397+0000] {docker.py:359} INFO - Starting docker container from image docker-operator-etl:1.0
[2024-04-13T00:55:10.678+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/app/src/main.py", line 4, in <module>
    from operations.task import mainer
ModuleNotFoundError: No module named 'operations.task'
[2024-04-13T00:55:10.864+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-04-13T00:55:10.866+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=example-docker-operator-dag, task_id=print_message, execution_date=20240413T005509, start_date=20240413T005510, end_date=20240413T005510
[2024-04-13T00:55:10.875+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task print_message (Docker container failed: {'StatusCode': 1}; 2676)
[2024-04-13T00:55:10.917+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-13T00:55:10.946+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
